basic_recognizer/urls.py
from django.urls import path
from . import views 

app_name = 'basic_recognizer'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

ramenai/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_recognizer.urls'))
]

basic_recognizer/models.py
from django.db import models
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image
import io, base64

graph = tf.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    IMAGE_SIZE = 224
    MODEL_FILE_PATH = 'basic_recognizer/ml_models/vgg16_transfer.h5'
    classes = ["shio ramen", "shoyu ramen", "miso ramen"]
    num_classes = len(classes)

    def predict(self):
        model = None
        global graph

        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0

            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict(X)[0]
            predited = result.argmax()
            percentage = int(result[predited] * 100)
            return self.classes[predited], percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()
            return 'data:' + img.file.content_type + ';base64,' + base64_img
            

basic_recognizer/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

basic_recognizer/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

def index(request):
    template = loader.get_template('basic_recognizer/index.html')
    context = {'form':PhotoForm()}
    return HttpResponse(template.render(context, request))

def predict(request):
    if not request.method == "POST":
        return redirect('basic_recognizer/index')

    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError('Formが不正です')

    photo = Photo(image=form.cleaned_data['image'])
    predicted, percentage = photo.predict()

    template = loader.get_template('basic_recognizer/result.html')

    context = {
        'photo_name': photo.image.name,
        'photo_data': photo.image_src(),
        'predicted': predicted,
        'percentage': percentage,
    }

    return HttpResponse(template.render(context, request))

basic_recognizer/templates/basic_recognizer/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'basic_recognizer/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <div class="jumbotron text-center d-flex align-items-center" style="height: 800px; background:url({% static 'basic_recognizer/img/main.jpg' %}); background-size:cover; background-position:center;">
      <div class="container">
        <h1 class="display-4" style="color: azure; font-family: fantasy; font-size: 80px;">RAMEN RECOGNITION APP</h1>
        <p class="lead" style="color: azure; font-family: fantasy; font-size: 30px;">The basic flavors are recognize into soy sauce, miso and salt.</p>
      </div>
    </div>
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

basic_recognizer/templates/basic_recognizer/index.html
{% extends 'basic_recognizer/base.html' %}
{% block title %}ラーメンアプリメニュー{% endblock %}

{% block content %}

<div>
    <h4 class="mt-4 mb-5 border-bottom" style="font-family: fantasy;">Ramen type recognition</h4>
    <p style="font-family: fantasy;">Select an image file and click the recognition button.</p>
    <form action="{% url 'basic_recognizer:predict' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <div class="custom-file">
            {{ form.image }}
            <label class="custom-file-label" for="customFile" style="font-family: Arial, Helvetica, sans-serif;">
                Select the file you want to recognize.
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary" style="font-family: fantasy;">Recognize</button>
    </form> 

</div>
{% endblock %}

basic_recognizer/templates/basic_recognizer/result.html
{% extends 'basic_recognizer/base.html' %}
{% block title %}ラーメン判別アプリメニュー{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom" style="font-family: fantasy;">Result</h4>

    <table class='table'>
        <tbody>
            <tr>
                <td style="font-family: fantasy;">NAME</td>
                <td style="font-family: fantasy;">{{ photo_name }}</td>
            </tr>
            <tr>
                <td style="font-family: fantasy;">IMAGE</td>
                <td style="font-family: fantasy;"><img class='preview-img' src={{ photo_data }} width=224, height=224></img></td>
            </tr>
            <tr>
                <td style="font-family: fantasy;">Types of ramen</td>
                <td style="font-family: fantasy;">{{ predicted }}</td>
            </tr>
            <tr>
                <td style="font-family: fantasy;">Recognition probability</td>
                <td style="font-family: fantasy;">{{ percentage }}%</td>

            </tr>
        </tbody>
    </table>

    <a href = "{% url 'basic_recognizer:index' %}" class="btn btn-primary" style="font-family: fantasy;">BACK</a>

</div>
{% endblock %}